spring:
  application:
    name: digital-asset-management-service
    title: DIGITAL-ASSET-MANAGEMENT-SERVICE
  datasource:
    platform: h2
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true